server:
  port: 7070

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

spring:
  cloud:
    gateway:
      routes:

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/userservice/**

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/authservice/**

        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/accountservice/**

        - id: transaction-service
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/transactionservice/**

        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notifications/**
