spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userservice
    username: postgres
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082

jwt:
  secret: qF6WQ9h+9H8QK9g6M8qK6r3w6q1v3q4M2sJ2QxY7V2Q=
  expiration: 3600000

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always
